version: '3.8'
services:
  backend:
    build: './backend'
    env_file: './backend/.env'
    environment:
      - SITE_URL=http://frontend-1:3000
    ports:
      - '8080:8080'
    volumes:
      - './backend:/app'
      - '/app/node_moudles'
  frontend:
    build: './frontend'
    env_file: './frontend/.env'
    environment:
      - NEXT_PUBLIC_SERVER_PATH=http://backend-1:8080
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
      - '/app/node_moudles'
    tty: true
    depends_on:
      - backend
